/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "echo.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
echo_1(char *s, char **clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, echo,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &s,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}
