/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ECHO_H_RPCGEN
#define _ECHO_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


#define ECHOPROG 420
#define ECHOPROGVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define echo 2
extern  enum clnt_stat echo_1(char *, char **, CLIENT *);
extern  bool_t echo_1_svc(char *, char **, struct svc_req *);
extern int echoprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define echo 2
extern  enum clnt_stat echo_1();
extern  bool_t echo_1_svc();
extern int echoprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ECHO_H_RPCGEN */
